package PageFrame;
import Tree.MapPanel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;

public class LecturerPage extends javax.swing.JFrame {

    private CardLayout cardLayout = new CardLayout();

    public LecturerPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        outerPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        Usericon = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        courseComboBox = new javax.swing.JComboBox<>();
        insertFileButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outerPanel.setBackground(new java.awt.Color(2, 188, 119));
        outerPanel.setPreferredSize(new java.awt.Dimension(800, 60));

        usernameLabel.setBackground(new java.awt.Color(255, 255, 255));
        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username");
        usernameLabel.setPreferredSize(new java.awt.Dimension(100, 30));

        Usericon.setIcon(new javax.swing.ImageIcon("src/Image/userImage.jpg")); // NOI18N
        Usericon.setToolTipText("");

        confirmButton.setIcon(new javax.swing.ImageIcon("src/Image/confirmButtonImage.png")); // NOI18N
        confirmButton.setPreferredSize(new java.awt.Dimension(30, 30));
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });

        insertFileButton.setText("EDIT");
        insertFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                insertFileButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(outerPanel);
        outerPanel.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(courseComboBox, 0, 237, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(insertFileButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                                .addComponent(Usericon)
                                .addGap(28, 28, 28)
                                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Usericon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(courseComboBox)
                                                        .addComponent(confirmButton, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                                        .addComponent(insertFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11))
        );

        getContentPane().add(outerPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(cardLayout);
        // Set default centerPanel
        JPanel blankPanel = new JPanel();
        blankPanel.setPreferredSize(new Dimension(800, 449));
        centerPanel.add(blankPanel, BorderLayout.CENTER);
        centerPanel.add(blankPanel, "blankPanel");

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // Clear centerPanel to remove any existing components
        //centerPanel.removeAll();

        // Create the MapPanel dynamically and add it to centerPanel
        MapPanel mapPanel = new MapPanel("src/CourseObjFile/Course_CPE.ser");
        centerPanel.add(mapPanel, "mapPanel");

        // Show the newly added mapPanel
        cardLayout.show(centerPanel, "mapPanel");

        // Refresh/revalidate centerPanel to apply changes
        centerPanel.revalidate();
        centerPanel.repaint();
    }

    private void insertFileButtonMouseClicked(MouseEvent evt) {
//        JPanel blankPanel = new JPanel();
//        blankPanel.setPreferredSize(new Dimension(800, 449));
//        centerPanel.add(blankPanel, BorderLayout.CENTER);
//        centerPanel.add(blankPanel);

        cardLayout.show(centerPanel, "blankPanel");
        centerPanel.revalidate();
        centerPanel.repaint();
    }

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            //
        }

        JFrame mainFrame = new LecturerPage();
        mainFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        mainFrame.setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JButton confirmButton;
    private javax.swing.JLabel Usericon;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JButton insertFileButton;
    private javax.swing.JPanel outerPanel;
    private javax.swing.JPanel centerPanel;
    // End of variables declaration
}