package PageFrame;
import AllUser.User;
import FilePath.PathCourseSet;
import Tree.MapPanel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;

public class StudentPage extends JFrame {

    public StudentPage(User user) {
        this.setTitle("Student -->");
        this.user = user;
        this.fullName = user.getFullName()+" "+user.getLastName();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            //
        }

        String[] courseName = PathCourseSet.getCourseName();

        if (courseName != null) {
            courseComboBox = new JComboBox<>(courseName);
        } else {
            courseComboBox = new JComboBox<>();
        }

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        headerPanel = new JPanel();
        usernameLabel = new JLabel();
        Usericon = new JLabel();
        confirmButton = new JButton();
        resetButton = new JButton();
        centerPanel = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new Color(2, 188, 119));
        headerPanel.setPreferredSize(new Dimension(800, 60));

        usernameLabel.setBackground(new Color(255, 255, 255));
        usernameLabel.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        usernameLabel.setForeground(new Color(255, 255, 255));
        usernameLabel.setText("Username");
        usernameLabel.setPreferredSize(new Dimension(100, 30));
        usernameLabel.setText(fullName);

        Usericon.setIcon(new ImageIcon("src/Image/userImage.jpg")); // NOI18N
        Usericon.setToolTipText("");

        confirmButton.setIcon(new ImageIcon("src/Image/confirmButtonImage.png")); // NOI18N
        confirmButton.setPreferredSize(new Dimension(30, 30));
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });

        courseComboBox.setFont(new Font("Segoe UI", Font.PLAIN, 16));


        resetButton.setText("Reset");
        resetButton.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        GroupLayout headerPanelLayout = new GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(courseComboBox, GroupLayout.PREFERRED_SIZE, 239, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confirmButton, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(Usericon)
                                .addGap(28, 28, 28)
                                .addComponent(usernameLabel, GroupLayout.PREFERRED_SIZE, 152, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Usericon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(headerPanelLayout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addGroup(headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(courseComboBox)
                                                        .addComponent(confirmButton, GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                                                        .addComponent(resetButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 2, GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11))
        );

        getContentPane().add(headerPanel, BorderLayout.NORTH);

        centerPanel.setLayout(cardLayout);
        // Set default centerPanel
        JPanel blankPanel = new JPanel();
        blankPanel.setPreferredSize(new Dimension(800, 449));
        centerPanel.add(blankPanel, BorderLayout.CENTER);
        centerPanel.add(blankPanel, "blankPanel");

        getContentPane().add(centerPanel, BorderLayout.CENTER);
        pack();
    }// </editor-fold>

    private void confirmButtonMouseClicked(MouseEvent evt) {
        // Clear centerPanel to remove any existing components
        centerPanel.removeAll();

        String courseName = (String) courseComboBox.getSelectedItem();

        MapPanel mapPanel = new MapPanel(PathCourseSet.getPathOf(courseName));
        centerPanel.add(mapPanel, "mapPanel");

        // Show the newly added mapPanel
        cardLayout.show(centerPanel, "mapPanel");

        // Refresh/revalidate centerPanel to apply changes
        centerPanel.revalidate();
        centerPanel.repaint();
    }

    private void resetButtonMouseClicked(MouseEvent evt) {
        centerPanel.removeAll();

        JPanel blankPanel = new JPanel();
        blankPanel.setPreferredSize(new Dimension(800, 449));
        centerPanel.add(blankPanel, BorderLayout.CENTER);
        centerPanel.add(blankPanel);

        cardLayout.show(centerPanel, "blankPanel");
        centerPanel.revalidate();
        centerPanel.repaint();
    }

    public void updateCourseComboBox() {
            String[] courseNames = PathCourseSet.getCourseName();

            // Clear existing items from the combo box
            courseComboBox.removeAllItems();

            // Add each course name to the combo box
            if (courseNames != null) {
                for (String courseName : courseNames) {
                    courseComboBox.addItem(courseName);
                }
            }

            // Repaint to make sure the UI is updated
            courseComboBox.revalidate();
            courseComboBox.repaint();

    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        try {
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
//        } catch (Exception e) {
//            //
//        }
//
//        JFrame mainFrame = new StudentPage();
//        mainFrame.setExtendedState(JFrame.MAXIMIZED_BOTH);
//        mainFrame.setVisible(true);
//    }

    // Variables declaration - do not modify
    private final CardLayout cardLayout = new CardLayout();
    private JComboBox<String> courseComboBox;
    private JButton confirmButton;
    private JButton resetButton;
    private JLabel Usericon;
    private JLabel usernameLabel;
    private JPanel headerPanel;
    private JPanel centerPanel;
    private User user;
    private String fullName;
    // End of variables declaration
}