package JarMainPage;

import CourseMap.ColorMap;
import CourseMap.MapPanel;
import FilePath.CourseFileCreatePanel;
import FilePath.JarCourseCreatePanel;
import FilePath.PathCourseSet;
import Login_Register_Page.Login;
import Users.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class MainPage extends JFrame {

    public MainPage() {
        this.setTitle("CourseMap");
        this.user = null;
        this.fullName = "";

        String[] courseName = PathCourseSet.getCourseName();

        if (courseName != null) {
            courseComboBox = new JComboBox<>(courseName);
        } else {
            courseComboBox = new JComboBox<>();
        }

        initComponents();
        setMinimumSize(new Dimension(1245, 720));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        headerPanel = new JPanel();
        usernameLabel = new JLabel();
        Usericon = new JLabel();
        resetButton = new JButton();
        insertFileButton = new JButton();
        centerPanel = new JPanel();
        resetAllowed = false;

        colorPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(Color.white);

                // Draw rounded rectangle with the specified corner radius
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 10, 10);
                g2.dispose();
            }
        };

        escDispatcher = e -> {
          if (e.getID() == KeyEvent.KEY_PRESSED && e.getKeyCode() == KeyEvent.VK_ESCAPE) {
              KeyboardFocusManager.getCurrentKeyboardFocusManager().removeKeyEventDispatcher(escDispatcher);
              new Login();
              dispose();
              return true;
          }
          return false;
        };

        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(escDispatcher);

        requireBoxLabel = new JLabel();
        requireLabel = new JLabel();
        nextBoxLabel = new JLabel();
        nextLabel = new JLabel();
        currentLabel = new JLabel();
        currentBoxLabel = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBackground(new Color(2, 188, 119));
        headerPanel.setPreferredSize(new Dimension(800, 65));

        usernameLabel.setBackground(new Color(255, 255, 255));
        usernameLabel.setFont(new Font("Segoe UI", Font.PLAIN, 17)); // NOI18N
        usernameLabel.setForeground(new Color(255, 255, 255));
        usernameLabel.setText("Username");
        usernameLabel.setPreferredSize(new Dimension(100, 30));
        usernameLabel.setText(fullName);

        Usericon.setIcon(new ImageIcon("src/resource/Image/userImage.jpg")); // NOI18N
        Usericon.setToolTipText("");

        courseComboBox.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        courseComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                comboBoxActionEvent(evt);
            }
        });

        insertFileButton.setText("INSERT");
        insertFileButton.setFocusPainted(false);
        insertFileButton.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        insertFileButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                insertFileButtonMouseClicked(e);
            }
        });

        resetButton.setText("RESET");
        resetButton.setFocusPainted(false);
        resetButton.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        resetButton.setBackground(Color.WHITE);
        resetButton.setForeground(Color.BLACK);
        resetButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        colorPanel.setPreferredSize(new Dimension(400, 30));
        colorPanel.setLayout(new GridBagLayout());
        colorPanel.setOpaque(false);

        GridBagConstraints gridBagConstraints;

        currentBoxLabel.setBackground(ColorMap.ACTIVE_CLICKED_NODE_COLOR);
        currentBoxLabel.setBorder(BorderFactory.createLineBorder(ColorMap.BORDER_ACTIVE_NODE_COLOR,2));
        currentBoxLabel.setOpaque(true);
        currentBoxLabel.setPreferredSize(new Dimension(21, 21));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(8, 30, 0, 0);
        colorPanel.add(currentBoxLabel, gridBagConstraints);

        nextBoxLabel.setBackground(ColorMap.ACTIVE_TARGET_NODE_COLOR);
        nextBoxLabel.setOpaque(true);
        nextBoxLabel.setPreferredSize(new Dimension(25, 25));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(8, 34, 0, 0);
        colorPanel.add(nextBoxLabel, gridBagConstraints);

        requireBoxLabel.setBackground(ColorMap.ACTIVE_SOURCE_NODE_COLOR);
        requireBoxLabel.setOpaque(true);
        requireBoxLabel.setPreferredSize(new Dimension(25, 25));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(8, 22, 0, 0);
        colorPanel.add(requireBoxLabel, gridBagConstraints);

        requireLabel.setText("Require");
        requireLabel.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(0, 12, 0, 0);
        colorPanel.add(requireLabel, gridBagConstraints);

        currentLabel.setText("Current");
        currentLabel.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(0, 18, 0, 0);
        colorPanel.add(currentLabel, gridBagConstraints);

        nextLabel.setText("Next");
        nextLabel.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new Insets(0, 12, 0, 28);
        colorPanel.add(nextLabel, gridBagConstraints);



        GroupLayout headerPanelLayout = new GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
                headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(courseComboBox, GroupLayout.PREFERRED_SIZE, 239, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGap(18, 18, 18)
                                .addComponent(resetButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(insertFileButton, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(colorPanel, GroupLayout.PREFERRED_SIZE, 383, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                                .addComponent(Usericon)
                                .addGap(23, 23, 23)
                                .addComponent(usernameLabel, GroupLayout.PREFERRED_SIZE, 200, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
                headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(headerPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2)
                                        .addComponent(Usericon, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(headerPanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(headerPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(courseComboBox)
                                                        .addComponent(insertFileButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(resetButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(colorPanel, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(11, 11, 11))
        );

        getContentPane().add(headerPanel, BorderLayout.NORTH);

        centerPanel.setLayout(cardLayout);
        // Set default centerPanel
        JPanel blankPanel = new JPanel();
        blankPanel.setPreferredSize(new Dimension(800, 449));
        centerPanel.add(blankPanel, BorderLayout.CENTER);
        centerPanel.add(blankPanel, "blankPanel");

        getContentPane().add(centerPanel, BorderLayout.CENTER);

        pack();
    }// </editor-fold>

    private void comboBoxActionEvent(ActionEvent evt) {
        centerPanel.removeAll();

        resetAllowed = true;
        String courseName = (String) courseComboBox.getSelectedItem();
        MapPanel mapPanel = new MapPanel(PathCourseSet.getPathOf(courseName));
        centerPanel.add(mapPanel, "mapPanel");

        cardLayout.show(centerPanel, "mapPanel");

        // Repaint to make sure the UI is updated
        centerPanel.revalidate();
        centerPanel.repaint();
    }

    private void insertFileButtonMouseClicked(MouseEvent e) {
        new JarCourseCreatePanel(this);
    }

    private void resetButtonMouseClicked(MouseEvent evt) {
        if (!resetAllowed) return;
        centerPanel.removeAll();
        String courseName = (String) courseComboBox.getSelectedItem();
        MapPanel mapPanel = new MapPanel(PathCourseSet.getPathOf(courseName));
        centerPanel.add(mapPanel, "mapPanel");

        cardLayout.show(centerPanel, "mapPanel");

        // Repaint to make sure the UI is updated
        centerPanel.revalidate();
        centerPanel.repaint();
    }

    public void updateCourseComboBox() {
            String[] courseNames = PathCourseSet.getCourseName();

            courseComboBox.removeAllItems();

            if (courseNames != null) {
                for (String courseName : courseNames) {
                    courseComboBox.addItem(courseName);
                }
            }

            // Repaint to make sure the UI is updated
            courseComboBox.revalidate();
            courseComboBox.repaint();

    }

    // Variables declaration - do not modify
    private boolean resetAllowed;
    private KeyEventDispatcher escDispatcher;
    private final CardLayout cardLayout = new CardLayout();
    private final JComboBox<String> courseComboBox;
    private JButton resetButton;
    private JLabel Usericon;
    private JLabel usernameLabel;
    private JButton insertFileButton;
    private JPanel headerPanel;
    private JPanel centerPanel;

    private JPanel colorPanel;
    private JLabel currentBoxLabel;
    private JLabel currentLabel;
    private JLabel nextBoxLabel;
    private JLabel nextLabel;
    private JLabel requireBoxLabel;
    private JLabel requireLabel;
    private User user;
    private String fullName;
    // End of variables declaration
}