/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FilePath;

import Course.CreateObjCourse;
import Function.Time;

import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author This pc
 */
public class CourseFileCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CourseFileCreatePanel
     */
    public CourseFileCreatePanel() {
        try {
            // this line make JFileChooser look and feel
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {

        }
        initComponents();
        fc.setMultiSelectionEnabled(true);
        fc.setCurrentDirectory(new File("C:\\"));
        // Call this panel to option pane
        JOptionPane.showMessageDialog(null, this, "CourseCreator", JOptionPane.PLAIN_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        javax.swing.JButton chooseButton;
        javax.swing.JButton createButton;
        javax.swing.JLabel fileLb;
        javax.swing.JLabel fileLb1;
        javax.swing.JLabel headerLb;
        javax.swing.JPanel insidePanel;
        javax.swing.JButton resetButton;

        insidePanel = new javax.swing.JPanel();
        headerLb = new javax.swing.JLabel();
        fileLb = new javax.swing.JLabel();
        filePathLb = new javax.swing.JLabel();
        chooseButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        statusLb = new javax.swing.JLabel();
        fileLb1 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();

        nameTextField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (nameTextField.getText().equals("Input Course Name")) {
                    nameTextField.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (nameTextField.getText().isEmpty()) {
                    nameTextField.setText("Input Course Name");
                }
            }
        });

        setBackground(new java.awt.Color(153, 255, 153));

        insidePanel.setBackground(new java.awt.Color(255, 255, 255));

        headerLb.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        headerLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLb.setText("Please input couse file within .csv -->");

        fileLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fileLb.setText("FilePath :");

        filePathLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        filePathLb.setText("C:\\\\");

        chooseButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chooseButton.setText("chooseFile");
        //chooseButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        chooseButton.setBackground(Color.white);
        chooseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseButtonMouseClicked(evt);
            }
        });

        resetButton.setText("reset");
        //resetButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        resetButton.setBackground(Color.white);
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        createButton.setText("Create courseFile");
        //createButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        createButton.setBackground(Color.white);
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });

        statusLb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        statusLb.setText("");

        fileLb1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        fileLb1.setText("Course: ");

        nameTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(102, 102, 102));
        nameTextField.setText("Input Course Name");

        javax.swing.GroupLayout insidePanelLayout = new javax.swing.GroupLayout(insidePanel);
        insidePanel.setLayout(insidePanelLayout);
        insidePanelLayout.setHorizontalGroup(
                insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(insidePanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(headerLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                        .addGroup(insidePanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(insidePanelLayout.createSequentialGroup()
                                                .addComponent(fileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(filePathLb, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(insidePanelLayout.createSequentialGroup()
                                                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(insidePanelLayout.createSequentialGroup()
                                                                .addComponent(chooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(28, 28, 28)
                                                .addComponent(statusLb, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(insidePanelLayout.createSequentialGroup()
                                                .addComponent(fileLb1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        insidePanelLayout.setVerticalGroup(
                insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(insidePanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(headerLb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fileLb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fileLb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(filePathLb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(chooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(insidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(statusLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addComponent(insidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addComponent(insidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
        );
    }// </editor-fold>

    private void chooseButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int returnVal = fc.showDialog(this, "Choose");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            filePathLb.setText(file.getPath()+"");
        }
    }

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        String filePath = filePathLb.getText().trim();

        if (nameTextField.getText().equals("Input Course Name")) { // Check if you didn't change name
            statusLb.setText("Please Input Name");
            Time.delay(1000, ()->statusLb.setText(""));
        } else if (filePath.equals("C:\\\\")) {
            statusLb.setText("Please Select FilePath");
            Time.delay(1000, ()->statusLb.setText(""));

        } else if (!filePath.toLowerCase().endsWith(".csv")) { // Check if the file path is a CSV file
            statusLb.setText("Not .csv file");
            Time.delay(1000, ()->statusLb.setText(""));

        } else { // Valid CSV file
            new CreateObjCourse(nameTextField.getText(),filePathLb.getText());
            Time.delay(1000, ()->statusLb.setText(""));
        }
    }

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        filePathLb.setText("C:\\\\");
        nameTextField.setText("Input Course Name");
        statusLb.setText("reset");
        Time.delay(1000, ()->statusLb.setText(""));
    }

    public static void main(String[] args) {
        new CourseFileCreatePanel();
    }

    private final JFileChooser fc = new JFileChooser();
    // Variables declaration - do not modify
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel filePathLb;
    private javax.swing.JLabel statusLb;
    // End of variables declaration
}
