/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FilePath;

import Course.CreateObjCourse;
import Function.Time;
import JarMainPage.MainPage;
import MainPage.LecturerPage;

import javax.swing.*;
import java.awt.*;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;

/**
 *
 * @author This pc
 */
public class JarCourseCreatePanel extends JPanel {

    /**
     * Creates new form CourseFileCreatePanel
     */
    public JarCourseCreatePanel(MainPage mainpage) {
        this.mainPage = mainpage;

        initComponents();
        fc.setMultiSelectionEnabled(false);
        fc.setCurrentDirectory(new File("C:\\"));
        // Call this panel to option pane
        JOptionPane.showMessageDialog(null, this, "CourseCreator", JOptionPane.PLAIN_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JButton chooseButton;
        JButton createButton;
        JLabel fileLb;
        JLabel fileLb1;
        JLabel headerLb;
        JPanel insidePanel;
        JButton resetButton;

        insidePanel = new JPanel();
        headerLb = new JLabel();
        fileLb = new JLabel();
        filePathLb = new JLabel();
        chooseButton = new JButton();
        resetButton = new JButton();
        createButton = new JButton();
        statusLb = new JLabel();
        fileLb1 = new JLabel();
        nameTextField = new JTextField();

        nameTextField.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (nameTextField.getText().equals("Input Course Name")) {
                    nameTextField.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (nameTextField.getText().isEmpty()) {
                    nameTextField.setText("Input Course Name");
                }
            }
        });

        setBackground(new Color(2, 188, 119));

        insidePanel.setBackground(new Color(255, 255, 255));

        headerLb.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        headerLb.setHorizontalAlignment(SwingConstants.CENTER);
        headerLb.setText("Please input couse file within .csv -->");

        fileLb.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        fileLb.setText("FilePath :");

        filePathLb.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        filePathLb.setText("C:\\\\");

        chooseButton.setFont(new Font("Segoe UI", 0, 14)); // NOI18N
        chooseButton.setText("chooseFile");
        //chooseButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        chooseButton.setBackground(Color.white);
        chooseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseButtonMouseClicked(evt);
            }
        });

        resetButton.setText("reset");
        //resetButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        resetButton.setBackground(Color.white);
        resetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetButtonMouseClicked(evt);
            }
        });

        createButton.setText("Create courseFile");
        //createButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        createButton.setBackground(Color.white);
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });

        statusLb.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        statusLb.setText("");

        fileLb1.setFont(new Font("Segoe UI", 0, 20)); // NOI18N
        fileLb1.setText("Course: ");

        nameTextField.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        nameTextField.setForeground(new Color(102, 102, 102));
        nameTextField.setText("Input Course Name");

        GroupLayout insidePanelLayout = new GroupLayout(insidePanel);
        insidePanel.setLayout(insidePanelLayout);
        insidePanelLayout.setHorizontalGroup(
                insidePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(insidePanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(headerLb, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                        .addGroup(insidePanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(insidePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(insidePanelLayout.createSequentialGroup()
                                                .addComponent(fileLb, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(filePathLb, GroupLayout.PREFERRED_SIZE, 417, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(insidePanelLayout.createSequentialGroup()
                                                .addGroup(insidePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(createButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(insidePanelLayout.createSequentialGroup()
                                                                .addComponent(chooseButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(resetButton, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)))
                                                .addGap(28, 28, 28)
                                                .addComponent(statusLb, GroupLayout.PREFERRED_SIZE, 180, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(insidePanelLayout.createSequentialGroup()
                                                .addComponent(fileLb1)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nameTextField, GroupLayout.PREFERRED_SIZE, 410, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        insidePanelLayout.setVerticalGroup(
                insidePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(insidePanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(headerLb, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(insidePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fileLb1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nameTextField))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(insidePanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(fileLb, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(filePathLb, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(insidePanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addComponent(chooseButton, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resetButton, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(insidePanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(statusLb, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(createButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(227, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(22, Short.MAX_VALUE)
                                .addComponent(insidePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(17, Short.MAX_VALUE)
                                .addComponent(insidePanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
        );
    }// </editor-fold>

    private void chooseButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int returnVal = fc.showDialog(this, "Choose");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            filePathLb.setText(file.getPath()+"");
        }
    }

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        String filePath = filePathLb.getText().trim();

        if (nameTextField.getText().equals("Input Course Name")) { // bin.Check if you didn't change name
            statusLb.setText("Please Input Name");
            Time.delay(1000, ()->statusLb.setText(""));
        } else if (filePath.equals("C:\\\\")) {
            statusLb.setText("Please Select FilePath");
            Time.delay(1000, ()->statusLb.setText(""));

        } else if (!filePath.toLowerCase().endsWith(".csv")) { // bin.Check if the file path is a CSV file
            statusLb.setText("Not .csv file");
            Time.delay(1000, ()->statusLb.setText(""));

        } else { // Valid CSV file
            new CreateObjCourse(nameTextField.getText(),filePathLb.getText());
            if (mainPage != null) {
                mainPage.updateCourseComboBox();
            }
            statusLb.setText("Updated Course");
            Time.delay(1000, ()->statusLb.setText(""));
        }
    }

    private void resetButtonMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        filePathLb.setText("C:\\\\");
        nameTextField.setText("Input Course Name");
        statusLb.setText("reset");
        Time.delay(1000, ()->statusLb.setText(""));
    }

    private final JFileChooser fc = new JFileChooser();
    private final MainPage mainPage;
    // Variables declaration - do not modify
    private JTextField nameTextField;
    private JLabel filePathLb;
    private JLabel statusLb;
    // End of variables declaration
}
